name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go 1.17.6
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.6'

      - name: Set up Go 1.18beta1
        run: go install golang.org/dl/go1.18beta1@latest

      - name: Check out code
        uses: actions/checkout@v2

      - name: Download dependencies
        run: go1.18beta1 mod download

      - name: Run tests
        run: go1.18beta1 test -v -race ./...

      - name: Build
        run: go1.18beta1 build
