name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go 1.18
        uses: actions/setup-go@v2
        with:
          go-version: '1.18'

      - name: Check out code
        uses: actions/checkout@v2

      - name: Download dependencies
        run: go download

      - name: Run tests
        run: go test -v -race ./...

      - name: Build
        run: go build
